apiVersion: v1
kind: ConfigMap
metadata:
  name: letters-config
  namespace: homelab
data:
  FIREBASE_PROJECT_ID: "kin-keeper-7a525"
  FIREBASE_CREDENTIALS_PATH: "/etc/firebase/firebase-service-account.json"
  DB_HOST: "postgres.homelab.svc.cluster.local"
  DB_PORT: "5432"
  DB_NAME: "homelab"
  DB_USER: "homelab"
  JAVA_TOOL_OPTIONS: "-XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0"
