apiVersion: apps/v1
kind: Deployment
metadata:
  name: letters-frontend
  namespace: homelab
  labels:
    app: letters-frontend
    env: homelab
    managed-by: kubectl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: letters-frontend
  template:
    metadata:
      labels:
        app: letters-frontend
        env: homelab
    spec:
      containers:
        - name: letters-frontend
          image: localhost:30500/homelab/letters-frontend:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "200m"
