---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: letters-db-secret
  namespace: homelab
spec:
  encryptedData:
    DB_PASSWORD: AgBc5F+Amql7saTZi/4pUInvOebuBAda37hNRT5cVOBhg6jTE5bNZeXE+3BXjILwN7mJ2cwgz0a0IHHaWN94M9lVEKoUiESUbl4cjiSOGrjCj+Zz3bFJaZdM+U5zaVPPuQWZfelGEXtszEItw1z6rmcZuCbSW2yj7QLi0egljtvLPAkt86UcEr5IM53z+qYsnrwd7Yt8CC+EtPGnaitL2Vggs71eOLKZyzN15whnTZUWXFVEuoX+wLGaw3fVsTNrxM2SEPTpDteEwe3x/XXQv1+E33xPqTA7aO4uHbNB7hiVjc+ac8ICx3EoqYGuTKw6W9glLUsI1ydkmHnFZMEXiGzoQW9Iyd6JnIL9rL4645B/yiQh9HaMLIxtm4y6lMecQtW8weqPTPRD8i9QdqQ4vVYnTvku39FL6afq+Hx1mLT15+Lyeu4mkbnhJmlcUDW8TFQnT+ifI7rMVauup9D6Ry9gG0pmD+qic0sr8i2IBj08MKo5God7U5+PPGtu1SkxtJqHjqvOW9EVr/VDutbImmz8BloUPfpX0QUBVyG8H5la15YycNQObFkuyDBIKdbpTjRrkKm6KNR9dusOfJuzI1kYL0BiGX3xeyl7PKdrmEJxh0TbWJf7O1F3upA45vulWrYKkceP9XAsTTHWagQvAuFYcCGQ/ywxCGLkO+EggCkBIPaI21QjUnWmwxZrtZP0DX3DH8/Wqr4YVH9IrNxnhs0hBFCWPZE=
  template:
    metadata:
      name: letters-db-secret
      namespace: homelab
